# Generated by Django 6.0.7 on 2026-07-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('creacion', 'Tarea creada'), ('aviso_vencimiento', 'Aviso de vencimiento (3 días)'), ('vencimiento_cumplido', 'Vencimiento cumplido')], max_length=30)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('detalle', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-enviado_en'],
            },
        ),
    ]
