# Generated by Django 6.0.7 on 2026-07-21 00:27

import evidencias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=evidencias.models.ruta_evidencia)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('comentario', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('anulada', models.BooleanField(default=False, help_text='No se borra evidencia; se marca como anulada para conservar trazabilidad.')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
